name: "Cronjob Manual"
on: workflow_dispatch

jobs:
    update-weather:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Generate BerlinWeather
              uses: huantt/weather-forecast@v1.0.6
              with:
                city: Eberswalde
                days: 1
                weather-api-key: ${{ secrets.WEATHER_API_KEY }}
                template-file: 'BerlinWeather.md.template'
                out-file: 'BerlinWeather.md'
            - name: Commit
              run: |
                if git diff --exit-code; then
                  echo "No changes to commit."
                  exit 0
                else
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "update"
                  git push origin main
                fi
